apiVersion: v1
kind: Pod
metadata:
   name: pavan-resource-request
spec:
   containers:
     - image: gcr.io/kuar-demo/kuard-amd64:1
       name: kaurd
       resources:
         requests: #requests are minimum resources required.
           cpu: "500m"
           memory: "128Mi"
       ports:
          - containerPort: 8080
            name: http
            protocol: TCP
