apiVersion: v1
kind: Pod
metadata:
   name: "pavan-multi-container-pod"
spec:
  restartPolicy: Never    #Without this Pod goes to CrashLoopBackOff state with debian continue to restart
  volumes:
    - name: "shared-path"
      emptyDir: {}
  containers:
     - name: nginx-container
       image: nginx
       volumeMounts:
          - name: "shared-path"
            mountPath: /usr/share/nginx/html
     - name: debian-container
       image: debian
       volumeMounts:
          - name: "shared-path"
            mountPath: "/pod-data"
       command: ["/bin/sh"]
       args: ["-c", "echo Hello from the debian container > /pod-data/index.html"]

      #  debian-container will be terminated after executing the command. you can execute below commands to see nginx now is responding with the "Hello from the debian container"

      #  $ kubectl exec -it pavan-multi-container -c nginx-container bash
      #  root@pavan-multi-container:/# curl localhost 
      #  Hello from the debian container       