apiVersion: v1
kind: Pod
metadata:
   name: "pavan-volume"
spec:
  volumes:              #Pod persistant volume example
    - name: 'my-volume'
      hostPath: 
        path: "/tmp"
  containers:
     - name: kuard
       image: gcr.io/kuar-demo/kuard-amd64:1
       volumeMounts:  #you can add same volume in multiple mount paths
          - name: "my-volume"
            mountPath: "/pavan" #can be anything /data /pavan /yourapp
       ports:
         - containerPort: 8080
           name: http
           protocol: TCP
