apiVersion: v1
kind: Pod
metadata:
   name: "pavan-remote-volume"
spec:
  volumes:
    - name: 'my-remote-volume'   #NFS remote server example
      nfs:
        server: my.nfs.server.local
        path: "/exports"
  containers:
     - name: kuard
       image: gcr.io/kuar-demo/kuard-amd64:1
       volumeMounts:  #you can add same volume in multiple mount paths
          - name: "my-remote-volume"
            mountPath: "/pavan" #can be anything /data /pavan /yourapp
       ports:
         - containerPort: 8080
           name: http
           protocol: TCP
