apiVersion: v1
kind: Pod
metadata:
   name: "pavan-volume"
spec:
  volumes:
    - name: 'my-volume'
      hostPath: 
        path: "/tmp"
  containers:
     - name: kuard
       image: gcr.io/kuar-demo/kuard-amd64:1
       volumeMounts:
          - name: "my-volume"
            mountPath: "/data"
       ports:
         - containerPort: 8080
           name: http
           protocol: TCP
